{
 "title": "Assetto Corsa Servers Players",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "AC DRIFT3RS Public Lobby! | Tando Buddies | Drift Playground",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "server_online_players_server_4{server_name=\"AC DRIFT3RS Public Lobby! | Tando Buddies | Drift Playground\"}"
    }
   ]
  },
  {
   "title": "Tetsa's Server",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "server_online_players_server_3{server_name=\"Tetsa's Drift Server!\"}"
    }
   ]
  },
  {
   "title": "AC DRIFT3RS Public Drift Server! | ADC Pack 420 | LA Canyons",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "server_online_players_server_5{server_name=\"AC DRIFT3RS Public Drift Server! | ADC Pack 420 | LA Canyons\"}"
    }
   ]
  },
  {
   "title": "Driver.27's Server",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "server_online_players_server_2{server_name=\"Driver.27's Drift Server \"}"
    }
   ]
  },
  {
   "title": "24/7! DRIFT3RS Public Lobby! | ADC Cars 420 Pack | Momiji",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "server_online_players_server_6{server_name=\"24/7! DRIFT3RS Public Lobby! | ADC Cars 420 Pack | Momiji \"}"
    }
   ]
  },
  {
   "title": "Sunny's Server",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "server_online_players_server_1{server_name=\"Sunny's drift server!\"}"
    }
   ]
  }
 ]
}